name: PHPUnit

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php:
          - '7.4'
          - '8.1'
        symfony:
          - '5.4.*'
          - '6.0.*'
        exclude:
          - php: '7.4'
            symfony: '6.0.*' # requires PHP ^8.0.2

    runs-on: ${{ matrix.os }}

    env:
      SYMFONY: ${{ matrix.symfony }}

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC'
          tools: composer:v2,flex

      - name: Install dependencies
        run: |
          composer update --prefer-dist
          vendor/bin/simple-phpunit install
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony }}"

      - name: Test
        run: |
          composer validate --strict --no-check-lock
          vendor/bin/simple-phpunit
